# Generated by Django 3.2.7 on 2021-09-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.company')),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('military_service_stat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HRRUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('salary', models.FloatField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('num_openings', models.IntegerField()),
                ('opening_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('is_man_or_intern', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('minimum_days', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.company')),
                ('hrr_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.hrruser')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_size', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.department')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_days', models.IntegerField()),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='EndUserEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='EndUserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('position', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.jobposting'),
        ),
        migrations.CreateModel(
            name='CoursesForInterShipApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField()),
                ('resume', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('gpa', models.FloatField(max_length=100)),
                ('standing', models.CharField(max_length=100)),
                ('num_days', models.IntegerField()),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser')),
            ],
        ),
    ]
