# Generated by Django 3.2.7 on 2021-09-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrruser',
            name='email',
        ),
    ]
