# Generated by Django 3.2.6 on 2021-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_remove_coursesforintershipapps_ciaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applyDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='beginDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eu_employer',
            name='beginDate',
            field=models.DateTimeField(),
        ),
    ]
