# Generated by Django 3.2.6 on 2021-08-31 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210805_0841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='CoursesForInterShipApps',
        ),
        migrations.DeleteModel(
            name='Employment_history',
        ),
        migrations.DeleteModel(
            name='Eu_emails',
        ),
        migrations.DeleteModel(
            name='Eu_employer',
        ),
        migrations.DeleteModel(
            name='hRRs',
        ),
        migrations.DeleteModel(
            name='InternshipJobPosting',
        ),
        migrations.DeleteModel(
            name='Manager_job_posting',
        ),
    ]
