# Generated by Django 3.2.6 on 2021-08-31 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20210831_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='kind',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_posting',
            name='minimumDays',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
