# Generated by Django 3.2.6 on 2021-09-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0009_remove_hrruser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='managerjobposting',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='managerjobposting',
            name='dept_size',
        ),
    ]
