# Generated by Django 3.2.6 on 2021-09-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0010_auto_20210913_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='minimum_days',
        ),
    ]
