# Generated by Django 3.2.6 on 2021-09-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0011_remove_jobposting_minimum_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndUserEmployer',
            new_name='Employer',
        ),
    ]
