# Generated by Django 3.2.6 on 2021-09-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0012_rename_enduseremployer_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduseremail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_basic.enduser'),
        ),
    ]
