# Generated by Django 3.2.6 on 2021-09-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0013_alter_enduseremail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser'),
        ),
        migrations.AlterField(
            model_name='enduseremail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.enduser'),
        ),
    ]
